### ISSUE TITLE
Request method to directly get phone number from facebook id

### ISSUE THREAD

**Issue by glerinsonum** [jacopotediosi/FacebookPhoneScanner#1]
@jacopotediosi non capisco niente cosa da questo script. 
chi sta una metoda, python get_info.py -id ( id of facebook ) -g ( get number )

**Comment by jacopotediosi** [comment]
You probably didn't understand how this script works. Please read the readme better.

**Comment by glerinsonum** [comment]
@jacopotediosi I have not understand your documentation. 
Example. 

Usage python example.py -id of user -s scope "number" location. 
What python version should for this and how is use of the installation

**Comment by jacopotediosi** [comment]
The script works on Python 2.x only (as you can see, print functions haven't parenthesis, for example).
Usage is just "python fps.py", and then you can set other parameters when requested from program.
If you want I can convert the entire project to english language: just let me know ;)

**Comment by glerinsonum** [comment]
@jacopotediosi You can make an video to understand what is this thing. :+1:

**Comment by glerinsonum** [comment]
@jacopotediosi 

Cordially thank you brother for your warm words. 

Is there any tool for Windows like said. 
Enter the id of facebook user. 
Waiting getting all publicily informations....

**Comment by glerinsonum** [comment]
@jacopotediosi Ciao Fratello. Mi spiega bene, How i can use this script. This script  need API KEY. 

How I can run or execute this script in Maltego CE .

**Comment by jacopotediosi** [comment]
@glerinsonum
No, this script doesn't need a Facebook Graph Api key. I would have written it into the documentation if it was needed.
Maltego has nothing to do with my script.
Are you sure to know what you are talking about?

**Comment by glerinsonum** [comment]
@jacopotediosi Ciao Bello. 

I would like to have an project with you, for Maltego Classic. 

Sincerely. Genti. 

Contact me on facebook. https://www.facebook.com/fravetto.naan
